"""
Alert orchestration: composes messages, de-duplicates by (alert_date,
signal_type), dispatches to configured channels, and logs every attempt to
`alert_events`.

"streamlit" channel delivery is a no-op here (there is nothing to send to
mid-request); the caller (a Streamlit page) is expected to render the
returned message via st.toast/st.success/st.warning after this module logs
it. Email and webhook channels perform real delivery.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date

from src import config
from src.alerts.email_service import EmailDeliveryError, send_email
from src.alerts.webhook_service import WebhookDeliveryError, send_webhook
from src.data.data_repository import alert_already_sent, insert_alert_event
from src.utils.logging_utils import get_logger

logger = get_logger(__name__)

CHANNEL_EMAIL = "email"
CHANNEL_WEBHOOK = "webhook"
CHANNEL_STREAMLIT = "streamlit"

ALERT_TYPE_BUY = "BUY"
ALERT_TYPE_SELL = "SELL"
ALERT_TYPE_PENDING = "PENDING_EXECUTION"
ALERT_TYPE_TRADE_EXECUTED = "TRADE_EXECUTED"
ALERT_TYPE_DEVIATION_THRESHOLD = "DEVIATION_THRESHOLD"
ALERT_TYPE_DATA_INGESTION_FAILED = "DATA_INGESTION_FAILED"
ALERT_TYPE_MODEL_UPDATE_FAILED = "MODEL_UPDATE_FAILED"

DISCLAIMER = (
    "This alert is generated by a rules-based research model and is not financial advice."
)


@dataclass
class AlertDispatchResult:
    sent: bool
    duplicate: bool
    message: str
    channel_results: dict = field(default_factory=dict)  # channel -> "SENT" | "FAILED: <reason>"


def build_signal_alert_message(
    signal_date: date,
    actual_close: float,
    predicted_trend_price: float,
    deviation_pct: float,
    signal_type: str,
    trade_amount_inr: float = config.DEFAULT_TRADE_AMOUNT_INR,
) -> tuple[str, str]:
    subject = f"NIFTY 50 Strategy Alert: {signal_type} Signal Generated"
    body = (
        f"Date: {signal_date}\n"
        f"Latest NIFTY Close: {actual_close:.2f}\n"
        f"Predicted Trend Price: {predicted_trend_price:.2f}\n"
        f"Deviation: {deviation_pct * 100:.2f}%\n"
        f"Signal: {signal_type}\n"
        f"Planned Execution: Next trading day open\n"
        f"Trade Amount: INR {trade_amount_inr:,.0f}\n\n"
        f"{DISCLAIMER}"
    )
    return subject, body


def _dispatch(alert_date: date, signal_type: str, subject: str, body: str, channels: list[str]) -> AlertDispatchResult:
    if alert_already_sent(alert_date, signal_type):
        logger.info("Skipping duplicate alert for %s / %s", alert_date, signal_type)
        return AlertDispatchResult(sent=False, duplicate=True, message=body, channel_results={})

    channel_results: dict = {}
    overall_sent = False
    for channel in channels:
        try:
            if channel == CHANNEL_EMAIL:
                send_email(subject, body)
                channel_results[channel] = "SENT"
                overall_sent = True
            elif channel == CHANNEL_WEBHOOK:
                send_webhook(f"{subject}\n\n{body}")
                channel_results[channel] = "SENT"
                overall_sent = True
            elif channel == CHANNEL_STREAMLIT:
                channel_results[channel] = "SENT"
                overall_sent = True
            else:
                channel_results[channel] = f"FAILED: unknown channel '{channel}'"
        except (EmailDeliveryError, WebhookDeliveryError) as exc:
            channel_results[channel] = f"FAILED: {exc}"
            logger.warning("Alert delivery failed on channel %s: %s", channel, exc)

        insert_alert_event(
            {
                "alert_date": alert_date,
                "signal_type": signal_type,
                "message": body,
                "delivery_channel": channel,
                "delivery_status": "SENT" if channel_results[channel] == "SENT" else "FAILED",
            }
        )

    return AlertDispatchResult(sent=overall_sent, duplicate=False, message=body, channel_results=channel_results)


def send_signal_alert(signal: dict, channels: list[str]) -> AlertDispatchResult:
    """signal: a row from strategy_signals (dict with signal_date, actual_close, ...)."""
    signal_type = signal["signal_type"]
    if signal_type not in (config.SIGNAL_BUY, config.SIGNAL_SELL):
        return AlertDispatchResult(sent=False, duplicate=False, message="No alert required for HOLD signals.")

    subject, body = build_signal_alert_message(
        signal_date=signal["signal_date"],
        actual_close=signal["actual_close"],
        predicted_trend_price=signal["predicted_trend_price"],
        deviation_pct=signal["deviation_pct"],
        signal_type=signal_type,
    )
    return _dispatch(signal["signal_date"], signal_type, subject, body, channels)


def send_pending_execution_alert(signal: dict, channels: list[str]) -> AlertDispatchResult:
    subject = f"NIFTY 50 Strategy Alert: {signal['signal_type']} Signal Pending Execution"
    body = (
        f"Date: {signal['signal_date']}\n"
        f"Signal: {signal['signal_type']}\n"
        "Execution is pending because next trading day open is unavailable.\n\n"
        f"{DISCLAIMER}"
    )
    return _dispatch(signal["signal_date"], ALERT_TYPE_PENDING, subject, body, channels)


def send_trade_executed_alert(trade: dict, channels: list[str]) -> AlertDispatchResult:
    subject = f"NIFTY 50 Strategy Alert: {trade['signal_type']} Trade Executed"
    body = (
        f"Signal Date: {trade['signal_date']}\n"
        f"Execution Date: {trade['execution_date']}\n"
        f"Execution Open Price: {trade['execution_open_price']:.2f}\n"
        f"Trade Amount: INR {trade['trade_amount_inr']:,.2f}\n"
        f"Units Traded: {trade['units_traded']:.4f}\n\n"
        f"{DISCLAIMER}"
    )
    return _dispatch(trade["execution_date"], ALERT_TYPE_TRADE_EXECUTED, subject, body, channels)


def send_deviation_threshold_alert(signal_date: date, deviation_pct: float, threshold_pct: float, channels: list[str]) -> AlertDispatchResult:
    subject = "NIFTY 50 Strategy Alert: Deviation Threshold Crossed"
    body = (
        f"Date: {signal_date}\n"
        f"Deviation: {deviation_pct * 100:.2f}% (threshold: {threshold_pct * 100:.2f}%)\n\n"
        f"{DISCLAIMER}"
    )
    return _dispatch(signal_date, ALERT_TYPE_DEVIATION_THRESHOLD, subject, body, channels)


def send_data_ingestion_failed_alert(alert_date: date, error_message: str, channels: list[str]) -> AlertDispatchResult:
    subject = "NIFTY 50 Strategy Alert: Data Ingestion Failed"
    body = f"Date: {alert_date}\nError: {error_message}\n\n{DISCLAIMER}"
    return _dispatch(alert_date, ALERT_TYPE_DATA_INGESTION_FAILED, subject, body, channels)


def send_model_update_failed_alert(alert_date: date, error_message: str, channels: list[str]) -> AlertDispatchResult:
    subject = "NIFTY 50 Strategy Alert: Model Update Failed"
    body = f"Date: {alert_date}\nError: {error_message}\n\n{DISCLAIMER}"
    return _dispatch(alert_date, ALERT_TYPE_MODEL_UPDATE_FAILED, subject, body, channels)
